### ISSUE TITLE
Access Denied when launching final solution add-in

### ISSUE THREAD

**Issue by anweiss** [OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials#5]
Getting an "Access denied. You do not have permission to perform this action or access this resource" when launching the FinalChainStoreAdd-in solution. Error seems to be originating from Line 119 in SharePointComponentDeployer.cs

```
Exception Details: Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.

Source Error: 


Line 117:                webScopedEmployeeAction.DeleteObject();
Line 118:
Line 119:                clientContext.ExecuteQuery();
Line 120:            }
Line 121:        }

Source File: C:\DevSamples\SharePoint_Provider-hosted_Add-ins_Tutorials\9_FinalChainStoreAdd-in\ChainStoreWeb\Utilities\SharePointComponentDeployer.cs    Line: 119 
```

**Comment by Rick-Kirkham** [comment]
I'm not able to reproduce this. A few thoughts: 
1. Be sure that you set the **Site URL** property of the project before you press F5. 
2. Try logging in as Admin to your Developer Site in the browser of your development computer before you press F5. Check the option to stay logged in.
3. When you press F5, do you get the prompt to grant the add-in **Full Control** permissions? 
4. Have you run other versions of the sample (i.e., not the final one) on this same SharePoint website? If so, there may be artifacts installed on it that the add-in is trying to install again. In particular, be sure to delete any **Local Employees** list from the **Site Contents** page of the SharePoint website before you press F5.

**Comment by anweiss** [comment]
I am logged in as an Admin to the site. I'm only prompted to "Trust" the add-in when pressing F5. I don't see any prompts for granting **Full Control**. I have also gone through and deleted the **Local Employees** list beforehand.

**Comment by Rick-Kirkham** [comment]
What permissions is the trust prompt asking for?

**Comment by mozrecook** [comment]
I am having the same issue for access denied at the same line as anweiss. As for the trust permissions prompt mentioned above, The permissions I am getting on the trust prompt are:  Let it have full control of this site collection.(I added this to see if it would help)  Let it have full control of this site. Let it have full control of the list: (Documents, Expected shipments,Microfeed,site assets and site pages ).  Is there a chance it could be a problem with the web config file as i am using V13 of SQL Express rather than V12?
